/*
 * Apache NiFi Registry REST API
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi_registry.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Permissions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-12T14:23:29.468928+02:00[Europe/Berlin]")
public class Permissions {
  @SerializedName("canRead")
  private Boolean canRead = null;

  @SerializedName("canWrite")
  private Boolean canWrite = null;

  @SerializedName("canDelete")
  private Boolean canDelete = null;

   /**
   * Indicates whether the user can read a given resource.
   * @return canRead
  **/
  @Schema(description = "Indicates whether the user can read a given resource.")
  public Boolean isCanRead() {
    return canRead;
  }

   /**
   * Indicates whether the user can write a given resource.
   * @return canWrite
  **/
  @Schema(description = "Indicates whether the user can write a given resource.")
  public Boolean isCanWrite() {
    return canWrite;
  }

   /**
   * Indicates whether the user can delete a given resource.
   * @return canDelete
  **/
  @Schema(description = "Indicates whether the user can delete a given resource.")
  public Boolean isCanDelete() {
    return canDelete;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Permissions permissions = (Permissions) o;
    return Objects.equals(this.canRead, permissions.canRead) &&
        Objects.equals(this.canWrite, permissions.canWrite) &&
        Objects.equals(this.canDelete, permissions.canDelete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canRead, canWrite, canDelete);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Permissions {\n");
    
    sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
    sb.append("    canWrite: ").append(toIndentedString(canWrite)).append("\n");
    sb.append("    canDelete: ").append(toIndentedString(canDelete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
