/*
 * Apache NiFi Registry REST API
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi_registry.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResourceDefinition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-12T14:23:29.468928+02:00[Europe/Berlin]")
public class ResourceDefinition {
  /**
   * The cardinality of the resource definition
   */
  @JsonAdapter(CardinalityEnum.Adapter.class)
  public enum CardinalityEnum {
    SINGLE("SINGLE"),
    MULTIPLE("MULTIPLE");

    private String value;

    CardinalityEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static CardinalityEnum fromValue(String input) {
      for (CardinalityEnum b : CardinalityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<CardinalityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CardinalityEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public CardinalityEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return CardinalityEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("cardinality")
  private CardinalityEnum cardinality = null;

  /**
   * Gets or Sets resourceTypes
   */
  @JsonAdapter(ResourceTypesEnum.Adapter.class)
  public enum ResourceTypesEnum {
    FILE("FILE"),
    DIRECTORY("DIRECTORY"),
    TEXT("TEXT"),
    URL("URL");

    private String value;

    ResourceTypesEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ResourceTypesEnum fromValue(String input) {
      for (ResourceTypesEnum b : ResourceTypesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ResourceTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResourceTypesEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ResourceTypesEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ResourceTypesEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("resourceTypes")
  private List<ResourceTypesEnum> resourceTypes = null;

  public ResourceDefinition cardinality(CardinalityEnum cardinality) {
    this.cardinality = cardinality;
    return this;
  }

   /**
   * The cardinality of the resource definition
   * @return cardinality
  **/
  @Schema(description = "The cardinality of the resource definition")
  public CardinalityEnum getCardinality() {
    return cardinality;
  }

  public void setCardinality(CardinalityEnum cardinality) {
    this.cardinality = cardinality;
  }

  public ResourceDefinition resourceTypes(List<ResourceTypesEnum> resourceTypes) {
    this.resourceTypes = resourceTypes;
    return this;
  }

  public ResourceDefinition addResourceTypesItem(ResourceTypesEnum resourceTypesItem) {
    if (this.resourceTypes == null) {
      this.resourceTypes = new ArrayList<ResourceTypesEnum>();
    }
    this.resourceTypes.add(resourceTypesItem);
    return this;
  }

   /**
   * The types of resources
   * @return resourceTypes
  **/
  @Schema(description = "The types of resources")
  public List<ResourceTypesEnum> getResourceTypes() {
    return resourceTypes;
  }

  public void setResourceTypes(List<ResourceTypesEnum> resourceTypes) {
    this.resourceTypes = resourceTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceDefinition resourceDefinition = (ResourceDefinition) o;
    return Objects.equals(this.cardinality, resourceDefinition.cardinality) &&
        Objects.equals(this.resourceTypes, resourceDefinition.resourceTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardinality, resourceTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceDefinition {\n");
    
    sb.append("    cardinality: ").append(toIndentedString(cardinality)).append("\n");
    sb.append("    resourceTypes: ").append(toIndentedString(resourceTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
